alter table negotiation add is_visible_client bool default true not null;
alter table negotiation add is_visible_supplier bool default true not null;
alter table negotiation add is_deleted bool default false not null;

update negotiation set is_visible_client = not exists (select 1 from state_blacklist where state_id=negotiation.state_id);
update negotiation set is_visible_supplier = not exists (select 1 from state_blacklist where state_id=negotiation.state_id);
drop table state_blacklist;

update client set negotiation_extra_fields = '{"admin": {"model": [{"key": "publisherId", "label": "Publisher ID"}, {"key": "email", "label": "email"}, {"key": "total_earnings_30_days", "label": "Total Earnings"}, {"key": "current_ads", "label": "Current Ads"}], "terms": [{"key": "values_label", "label": "New Ads"}, {"key": "export_terms.payment_terms_days", "label": "Payment Terms Days"}, {"key": "export_terms.kickback_percentage", "label": "Kickback Percentage"}, {"key": "export_terms.kickback_duration_months", "label": "Kickback Duration Months"}], "summary": []}, "client": {"model": [], "terms": [], "summary": []}}' where tag = 'adcash';
update client set negotiation_extra_fields = '{"admin": {"model": [{"key": "supplier_company_name", "label": "Supplier"}, {"key": "cogs_2019", "label": "COGS 2019"}, {"key": "link_to_contract", "label": "Contract"}, {"key": "platform", "label": "Platform"}], "terms": [{"key": "chatLastUpdateTime", "label": "Updated"}, {"key": "status", "label": "Dynamic Status"}, {"key": "agreed_value_text", "label": "Improvement"}, {"key": "agreed_value_absolute_text", "label": "Improved value"}], "summary": [{"key": "agreed_value_text", "type": "TEXT", "label": "New deals reached", "operation": "COUNT"}, {"key": "agreed_value_text", "type": "PERCENT", "label": "Average improvement", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Average improved value", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Total improved value", "operation": "SUM"}]}, "client": {"model": [{"key": "supplier_company_name", "label": "Supplier"}, {"key": "cogs_2019", "label": "COGS 2019"}, {"key": "link_to_contract", "label": "Contract"}, {"key": "platform", "label": "Platform"}], "terms": [{"key": "chatLastUpdateTime", "label": "Updated"}, {"key": "agreed_value_text", "label": "Improvement"}, {"key": "agreed_value_absolute_text", "label": "Improved value"}], "summary": [{"key": "agreed_value_text", "type": "TEXT", "label": "New deals reached", "operation": "COUNT"}, {"key": "agreed_value_text", "type": "PERCENT", "label": "Average improvement", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Average improved value", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Total improved value", "operation": "SUM"}]}}' where tag = 'wesco';
