ALTER TABLE client RENAME COLUMN negotiation_extra_fields TO negotiation_summary_fields;
ALTER TABLE client ADD negotiation_fields_config jsonb default '{}';

update client set negotiation_fields_config = '[{"type": "MODEL", "label": "Supplier", "format": "TEXT", "attribute": "supplier_company_name", "properties": 3}, {"type": "MODEL", "label": "COGS2019", "format": "CURRENCY", "attribute": "cogs_2019", "properties": 3}, {"type": "MODEL", "label": "Contract", "format": "LINK", "attribute": "link_to_contract", "properties": 3}, {"type": "MODEL", "label": "Platform", "format": "TEXT", "attribute": "platform", "properties": 3}, {"type": "TERM", "label": "Updated", "format": "TIME", "attribute": "chatLastUpdateTime", "properties": 3}, {"type": "TERM", "label": "DynamicStatus", "format": "TEXT", "attribute": "status", "properties": 1}, {"type": "TERM", "label": "Improvement", "format": "PERCENT", "attribute": "agreed_value_text", "properties": 3}, {"type": "TERM", "label": "Improvedvalue", "format": "CURRENCY", "attribute": "agreed_value_absolute_text", "properties": 3}]' where tag = 'wesco';
update client set negotiation_summary_fields = '{"admin": {"summary": [{"key": "agreed_value_text", "type": "NUMBER", "label": "New deals reached", "operation": "COUNT"}, {"key": "agreed_value_text", "type": "PERCENT", "label": "Average improvement", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Average improved value", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Total improved value", "operation": "SUM"}]}, "client": {"summary": [{"key": "agreed_value_text", "type": "NUMBER", "label": "New deals reached", "operation": "COUNT"}, {"key": "agreed_value_text", "type": "PERCENT", "label": "Average improvement", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Average improved value", "operation": "AVE"}, {"key": "agreed_value_absolute_text", "type": "CURRENCY", "label": "Total improved value", "operation": "SUM"}]}}' where tag = 'wesco';

update client set negotiation_fields_config = '[{"type": "MODEL", "label": "Publisher ID", "format": "TEXT", "attribute": "publisherId", "properties": 3}, {"type": "MODEL", "label": "Email", "format": "TEXT", "attribute": "email", "properties": 3}, {"type": "MODEL", "label": "Total Earnings", "format": "CURRENCY", "attribute": "total_earnings_30_days", "properties": 3}, {"type": "MODEL", "label": "Current Ads", "format": "TEXT", "attribute": "current_ads", "properties": 3}, {"type": "TERM", "label": "New Ads", "format": "TEXT", "attribute": "values_label", "properties": 3}, {"type": "TERM", "label": "Payment Terms Days", "format": "NUMBER", "attribute": "export_terms.payment_terms_days", "properties": 3}, {"type": "TERM", "label": "Kickback Percentage", "format": "NUMBER", "attribute": "export_terms.kickback_percentage", "properties": 3}, {"type": "TERM", "label": "Kickback Duration Months", "format": "NUMBER", "attribute": "export_terms.kickback_duration_months", "properties": 3}]' where tag = 'adcash';
update client set negotiation_summary_fields = '{}' where tag = 'adcash';
update client set negotiation_fields_config = '[{"type": "MODEL", "label": "Publisher ID", "format": "TEXT", "attribute": "publisherId", "properties": 3}, {"type": "MODEL", "label": "Email", "format": "TEXT", "attribute": "email", "properties": 3}, {"type": "MODEL", "label": "Total Earnings", "format": "CURRENCY", "attribute": "total_earnings_30_days", "properties": 3}, {"type": "MODEL", "label": "Current Ads", "format": "TEXT", "attribute": "current_ads", "properties": 3}, {"type": "TERM", "label": "New Ads", "format": "TEXT", "attribute": "values_label", "properties": 3}, {"type": "TERM", "label": "Payment Terms Days", "format": "NUMBER", "attribute": "export_terms.payment_terms_days", "properties": 3}, {"type": "TERM", "label": "Kickback Percentage", "format": "NUMBER", "attribute": "export_terms.kickback_percentage", "properties": 3}, {"type": "TERM", "label": "Kickback Duration Months", "format": "NUMBER", "attribute": "export_terms.kickback_duration_months", "properties": 3}]' where tag = 'adcashPoc';
update client set negotiation_summary_fields = '{}' where tag = 'adcashPoc';